SlicerDMRI/whitematteranalysis

bin/convert_ascii_vtk_to_binary.py
bin/wm_append_all.py
bin/wm_cluster_atlas.py
bin/wm_cluster_subject.py
bin/wm_label_from_atlas.py
bin/wm_laterality_all.py
bin/wm_mask_lines.py
bin/wm_measure_all_clusters.py
bin/wm_quality_control_tractography.py
bin/wm_register_multisubject.py
bin/wm_register_to_atlas.py
bin/wm_separate_clusters_by_hemisphere.py

This allows each of the commands to be run as command line tools across platforms.

Added standard python shebang to bin/ files

---

bin/wm_cluster_atlas.py

wm_cluster_atlas.py now has a #! line, and the --help isn't b0rked

Fixed stack on wm_cluster_atlas.py --help

---

bin/wm_register_multisubject_faster.py
whitematteranalysis/congeal_multisubject.py
whitematteranalysis/io.py
whitematteranalysis/register_two_subjects_nonrigid_bsplines.py

Fixed bugs--now b splines work as well as and better than previous thin plate spline implementation.

Test bspline params

---

bin/wm_quality_control_tractography.py

Hi Lauren,
Could you please update the code to support the relative html path for individual subject. Thanks! 
Regards,
Fan

EHN: relative path of individual html

---

bin/wm_quality_control_after_clustering.py
whitematteranalysis/cluster.py

Hi Lauren,
The following updates are used to fix the issue of displaying the histogram x-axis label.
Regards,
Fan

ENH: histogram x-axis label fix

---

README.md

Was going to link this on the mailing list, and saw it was a little hard to read.

Slight clean-up of README.md

---

bin/wm_append_cluster.py

Makes `wm_append_cluster.py` a stand-alone program.

Adds shebang for python removes extra Update

---

README.md
bin/wm_download_anatomically_curated_atlas.py
setup.py

Add a new script for downloading pre-provided atlases

---

tests/test_pipeline.sh
whitematteranalysis/cluster.py

With this change I can run all of test_pipeline in Slicer's VTK/Python.

Fix another VTK issue, and minor test_pipeline tweak

---

setup.py

Namely, this will allow wma to be installed via pip with:
```
pip install git+https://github.com/SlicerDMRI/whitematteranalysis
```
..which gets us very close to pypi-packageable.

More build fixes for clean environment

---

whitematteranalysis/wm_cluster_volumetric_measurements.py

Hi Lauren @ljod 
This code maps fiber clusters on a volumetric image (e.g. FA) and computes the mean, the max, etc. Also, it calculates the number of voxels and the volume size. I have double checked with comparison to the result form the LabelStatistics module in Slicer. They gave the same results. 
Regards,
Fan

Add compute cluster measures (eg FA) from a volumetric map

---

bin/wm_cluster_remove_outliers.py

Can be added now. We can later see if there are better options.

Parallelize outlier removal script

---

whitematteranalysis/io.py

fix nonrigid registeration

---

.github/workflows/test_package.yaml
setup.py

- ENH: Fix `pandas` version to 2.0.3
- ENH: Allow the test, package GHA workflow to run on pull requests

ENH: Fix `pandas` version to 2.0.3

---

doc/subject-specific-tractography-parcellation.md

Specify how the diffusion measurement module must be called in Linux.

DOC: Specify call to diffusion measurement module in Linux

---

README.md

- DOC: Increase consistency in SlicerDMRI citation message
- DOC: Prefer using https over http for SlicerDMRI web address
- DOC: Use Slicer's new documentation web addresses

DOC: Increase consistency in SlicerDMRI citation message

---

utilities/wm_compute_TAP.py

Remove non-meaningful comment.

DOC: Remove non-meaningful comment

---

bin/wm_compare_vtks.py
bin/wm_quality_control_tract_overlap.py
bin/wm_quality_control_tractography.py

Remove a comment that does not apply/is not relevant to the scripts
at issue.

DOC: Remove inaccurate comment

---

bin/wm_append_clusters.py
bin/wm_append_clusters_to_anatomical_tracts.py
bin/wm_assess_cluster_location_by_hemisphere.py
bin/wm_change_nrrd_dir.py
bin/wm_cluster_atlas.py
bin/wm_cluster_from_atlas.py
bin/wm_cluster_remove_outliers.py
bin/wm_cluster_volumetric_measurements.py
bin/wm_compare_vtks.py
bin/wm_create_mrml_file.py
bin/wm_diffusion_measurements.py
bin/wm_harden_transform.py
bin/wm_preprocess_all.py
bin/wm_quality_control_after_clustering.py
bin/wm_quality_control_tract_overlap.py
bin/wm_quality_control_tractography.py
bin/wm_register_multisubject_faster.py
bin/wm_register_to_atlas_new.py
bin/wm_remove_data_along_tracts.py
bin/wm_separate_clusters_by_hemisphere.py
bin/wm_tract_to_volume.py
bin/wm_vtp2vtk.py
utilities/wm_assess_cluster_location.py
utilities/wm_compute_FA_from_DWIs.py
utilities/wm_extract_clusters_by_endpoints.py
utilities/wm_flatten_length_distribution.py
utilities/wm_laterality_all.py
utilities/wm_measure_all_clusters.py
utilities/wm_measure_endpoint_overlap.py
utilities/wm_transform_polydata.py

Do not use `try/except` in non-optional package `import` statements.

STYLE: Do not use `try/except` in non-optional package imports

---

bin/wm_download_anatomically_curated_atlas.py

- STYLE: Remove unnecessary tab on blank line
- ENH: Allow specifying the atlas version at download
- ENH: Download atlas version metadata file

ENH: Allow specifying the atlas version at download

---

requirements.txt
setup.py

- ENH: Specify SciPy version for Python>=3.10
- ENH: Specify NumPy version for Python>=3.10

ENH: Fix requirements

---

setup.py

ENH: Auto-discover packages

---

.github/workflows/check_format.yml

ENH: Check code format on PRs

---

bin/wm_download_anatomically_curated_atlas.py
utilities/wm_fix_UKF_trace.py

Fix typos in printed messages.

DOC: Fix typos in printed messages

---

setup.py

Do not find packages in documentation folder.

ENH: Do not find packages in documentation folder

---

doc/conf.py

Exclude tests from documentation.

DOC: Exclude tests from documentation

---

README.md

Fix code format check badge in `README` file.

ENH: Fix code format check badge in `README` file

---

doc/index.rst

- DOC: Add a sentence about the purpose of WMA to the documentation index
- DOC: Add general and Python module index, and search page to doc index

DOC: Improve documentation index

---

setup.py

ENH: Bump version number to 0.4.0

---

setup.py

ENH: Start version 0.4.1

---

setup.py

ENH: Bump version to 0.4.1

---

setup.py

ENH: Start version 0.4.2

---

setup.py

ENH: Start version 0.4.3
