SlicerDMRI/whitematteranalysis

whitematteranalysis/similarity.py

We added a new distance method called Mean_shape to measure the similarity of two fiber tracts. This distance method is based on the mean distance and the angle shift of the directional vectors between two fiber tracts.

Add a distance method: Mean_shape

---

bin/wm_append_cluster.py
setup.py

Hi Lauren, 
Please see the script for appending the clusters. It takes the input e.g. 1,2,3 and generates a 'cluster_appended_1_2_3.vtp'. The point scalar 'cluster_idx' is added to view the fibers from different subjects. 
Regards,
Fan

Append multiple clusters into one vtp file 

---

bin/harden_transform_with_slicer.py
bin/wm_assess_cluster_location_by_hemisphere.py
bin/wm_harden_transform.py
bin/wm_separate_clusters_by_hemisphere.py

Hi Lauren, @ljod 
I made changes to the hemisphere separation code to store fiber location information (a pointdata named 'HemisphereLocation')  in the vtk file in the atlas space. In this way, after transforming the fiber clusters back to the original DWI space, we can use this information the perform hemisphere separation.
I have made some updates to the wiki for this, under 
`* wm_separate_clusters_by_hemisphere.py (in atlas space)`
`* wm_separate_clusters_by_hemisphere.py (in subject DWI space)`
In addition, I updated the wiki about the 'rigid_affine_fast' registration for brain tumor patient dataset, under
`* wm_register_to_atlas_new.py`
I added how to transform the fiber clusters back to the DWI space, under
`* wm_harden_transform.py`
Please let me know how do you feel. Thanks!!!! …

Add HemisphereLocation in fiber cluster vtk file

---

bin/wm_apply_ORG_atlas_to_subject.sh
bin/wm_diffusion_measurements.py

Slicer can be built standalone or downloaded. The current `wm_apply_ORG_atlas_to_subject.sh` script is compatible for a built Slicer that does not require various paths adjustment during execution. But it is not compatible with path adjusted Slicer commands. The incompatibility arises with the values accepted by `-s` and `-m` arguments.
* The `-s` accepted by `wm_apply_ORG_atlas_to_subject.sh` may not be just `Slicer`. For a shared `Slicer`, it can be `"AdditionalPaths=/path/to/SlicerDMRI /path/to/etc Slicer"`.
* Again, for a downloaded (not built) Slicer the `-m` argument can be `"Slicer --launch /path/to/Slicer-4.10/cli-modules/FiberTractMeasurements"`.
To support all such values of `-s` and `-m`, [`$SlicerPath`](https://github.com/SlicerDMRI/whitematteranalysis/blob/master/bin/wm_apply_ …

Slicer module

---

README.md

This apostrophe was a special character `O\xe2\x80\x99Donnell` which prevented ascii decoding of README.md

Fix apostrophe in O'Donnell

---

bin/harden_transform_with_slicer.py
bin/wm_append_clusters.py
bin/wm_append_clusters_to_anatomical_tracts.py
bin/wm_assess_cluster_location_by_hemisphere.py
bin/wm_cluster_from_atlas.py
bin/wm_cluster_remove_outliers.py
bin/wm_download_anatomically_curated_atlas.py
bin/wm_quality_control_after_clustering.py
bin/wm_quality_control_tractography.py
bin/wm_separate_clusters_by_hemisphere.py
bin/wm_vtp2vtk.py
setup.py
utilities/wm_assess_cluster_location.py
utilities/wm_compute_FA_from_DWIs.py
utilities/wm_extract_cluster.py
utilities/wm_extract_clusters_by_endpoints.py
utilities/wm_flatten_length_distribution.py
utilities/wm_measure_all_clusters.py
utilities/wm_measure_endpoint_overlap.py
utilities/wm_statistics.py
whitematteranalysis/cluster.py
whitematteranalysis/io.py
whitematteranalysis/render.py
whitematteranalysis/tract_measurement.py

This PR uses [`pyupgrade`](https://github.com/asottile/pyupgrade) to automatically upgrade python syntax to newer versions. The script listed below was run for Python 3.6+ syntax with changes committed.
- Install: `Python -m pip install pyupgrade`
- Running:
- On 1 file: `Python -m pyupgrade --py36-plus MyPythonFile.py`
- On multiple files: Here is my pyupgrade-script.py written to automate running pyupgrade across all python files in the repo. It was run by `Python pyupgrade-script.py`.
```python
import os
import subprocess
search_directory = "C:/Users/JamesButler/Documents/GitHub/whitematteranalysis"
for root, _, files in os.walk(search_directory):
for file_item in files:
file_path = os.path.join(root, file_item)
if os.path.isfile(file_path) and file_path.endswith(".py"): …
```

STYLE: Upgrade python syntax to 3.6 and newer

---

bin/harden_transform_with_slicer.py

As of the commit linked below, Slicer assumes that models with no explicitly declared space should be LPS.  For FiberBundles, SlicerDMRI explicitly defines the contents to be RAS if the space is not declared, for backwards compatibility.
The change in the commit uses the `loadFiberBundle` method to explicitly use the SlicerDMRI reader so that the tracts are correctly interpreted.
The `loadFiberBundle` method existed in 4.10.2 (actually since 2011) so no current users should have any problem with this change.
https://github.com/Slicer/Slicer/commit/6036edbc4b67712822ccb4ee89139cab1cbce3f2

BUG: fix transform hardening for Slicer

---

README.md
bin/wm_apply_ORG_atlas_to_subject.sh
bin/wm_assess_cluster_location_by_hemisphere.py
bin/wm_average_tract_measures.py
bin/wm_cluster_volumetric_measurements.py
bin/wm_diffusion_measurements.py
bin/wm_quality_control_after_clustering.py
bin/wm_register_multisubject_faster.py
bin/wm_register_to_atlas_new.py
bin/wm_separate_clusters_by_hemisphere.py
doc/subject-specific-tractography-parcellation.md
utilities/wm_fix_UKF_trace.py
utilities/wm_measure_endpoint_overlap.py

Fix miscellaneous typos and grammar across files, including hard-coded names for scripts and Slicer modules.
Use the appropriate case to refer to the `macOS` OS.

DOC: Fix miscellaneous typos and grammar across files

---

README.md
doc/bundles.md

DOC: Add bundle name list

---

.github/workflows/test_package.yaml
README.md
setup.py

Add GitHub actions build, test workflow file for CI.
Pin the dependencies in the setup file.
Add the corresponding status badge to the `README` file.

ENH: Add GitHub actions build, test workflow file for CI

---

doc/subject-specific-tractography-parcellation.md

Fix typo in subject-specific tractography parcellation documentation file.

DOC: Fix typo in subject-specific tractography parcellation doc file

---

bin/wm_preprocess_all.py
whitematteranalysis/filter.py

- ENH: Make tractogram downsampling results reproducible by default
- ENH: Allow non-identical results in tractogram downsampling

ENH: Make tractogram downsampling results reproducible by default

---

bin/wm_apply_ORG_atlas_to_subject.sh
doc/subject-specific-tractography-parcellation.md

Add a command line option to apply a transformation to the obtained tractography data. Relevant for data where the brain size of the subject is significantly different (e.g. infant data) from an adult's brain size (used for the ORG atlas). The option allows to apply a scaling transformation so that the registration process to the ORG atlas data can work reasonably. The inverse transformation is automatically applied after the clustering process has finished in case the transformation file is provided.
Document the use of the transform in documentation file.

ENH: Add a command line option to apply a transformation

---

License.txt

Sync the license file with the current Slicer license file content: https://github.com/Slicer/Slicer/blob/ce1ab3d3799ca9e11cc1175f4d0c8653d4837e11/License.txt
Specifically:
- Prefer using https over http for web addresses when available.
- Fix a typo following: https://github.com/Slicer/Slicer/commit/68ff0ae7114e4378322740f117643d7513a71110
- Add a blank line at the beginning of the file and remove an unnecessary whitespace in the text.
Make the filename be all lowercase to sync with the Slicer license filename.

DOC: Sync the license file with the current Slicer license file content

---

requirements.txt
setup.py

Remove unnecessary `Cython` package dependendency: WMA does not contain C extension code for Python.

ENH: Remove unnecessary `Cython` package dependendency

---

setup.py

Prefer using lowercase to name package in line with other relevant scientific computing Python packages.
Change it as well in the commented PyPI URL (note that the package was never been uploaded to PyPI, and thus, changing the package name at this stage is safe from that point of view).

STYLE: Prefer using lowercase to name package

---

README.md

Improve Markdown syntax in `README` file:
- Use simple backticks for inline verbatim code.
- Use triple backticks and shell highlighting hint for multi-line commands.
Split long commands over multiple lines to improve readability.
Add dollar sign in terminal commands.

DOC: Improve Markdown syntax in `README` file

---

bin/wm_append_clusters_to_anatomical_tracts.py
bin/wm_append_diffusion_measures_across_subjects.py
bin/wm_average_tract_measures.py
bin/wm_change_nrrd_dir.py
utilities/wm_assess_cluster_location.py
utilities/wm_compute_FA_from_DWIs.py
utilities/wm_compute_TAP.py
utilities/wm_extract_cluster.py
utilities/wm_extract_clusters_by_endpoints.py
utilities/wm_flatten_length_distribution.py
utilities/wm_laterality_all.py
utilities/wm_measure_all_clusters.py
utilities/wm_measure_endpoint_overlap.py
utilities/wm_statistics.py
utilities/wm_statistics_export_data.py
utilities/wm_transform_polydata.py

Define `main` methods to contain computation logic across scripts.

ENH: Define `main` methods to contain computation logic across scripts

---

.github/workflows/test_package.yaml
requirements.txt
setup.py

- ENH: Relax `numpy` install requirement version
- ENH: Add all released Python version above 3.8 until 3.11 to CI

ENH: Add all released Python version above 3.8 until 3.11 to CI

---

.readthedocs.yaml
README.md
doc/Makefile
doc/conf.py
doc/index.rst
doc/make.bat
setup.py

DOC: Add `readthedocs` documentation site infrastructure
Add `readthedocs` documentation site configuration and site index files.
Add the necessary packages to generate the documentation from the source
files, including Python module methods, and script arguments.
Add `Makefile` and `make.bat` files to build the documentation locally.
Add the reference to the `readthedocs` website and the corresponding
build badge to the `README` file.

DOC: Add `readthedocs` documentation site infrastructure

---

.github/workflows/test_package.yaml

Bump `checkout` GHA to v4 in workflows.

ENH: Bump `checkout` GHA to v4 in workflows

---

setup.py

Remove unused `pkg_resources` module import.
Also, `pkg_resources` is deprecated in recent `setuptools` versions.
Fixes:
```
* Getting build dependencies for wheel...
<string>:5: DeprecationWarning: pkg_resources is deprecated as an API.
See https://setuptools.pypa.io/en/latest/pkg_resources.html
* Installing packages in isolated environment... (numpy>=1.20.0, wheel)
* Building wheel...
<string>:5: DeprecationWarning: pkg_resources is deprecated as an API.
See https://setuptools.pypa.io/en/latest/pkg_resources.html
```
when trying to upload the package to TestPyPI using `$ twine upload --repository testpypi dist/*`
Documentation:
https://setuptools.pypa.io/en/latest/pkg_resources.html

ENH: Remove unused `pkg_resources` module import

---

bin/wm_compare_vtks.py
utilities/wm_flatten_length_distribution.py
utilities/wm_statistics.py
utilities/wm_statistics_export_data.py
utilities/wm_transform_polydata.py

Remove non-existing `version` keyword parameter in script argument parser object instantiation.
Fixes:
```
Traceback (most recent call last):
File ".virtualenvs/wma/lib/python3.8/site-packages/pytest_console_scripts/__init__.py", line 319, in exec_script
exec(compiled, {'__name__': '__main__'})
File ".virtualenvs/wma/bin/wm_flatten_length_distribution.py", line 4, in <module>
__import__('pkg_resources').run_script('whitematteranalysis==0.3.0', 'wm_flatten_length_distribution.py')
File ".virtualenvs/wma/lib/python3.8/site-packages/pkg_resources/__init__.py", line 666, in run_script
self.require(requires)[0].run_script(script_name, ns)
File ".virtualenvs/wma/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1462, in run_script
exec(code, namespace, namespace)
File …
```

BUG: Remove non-existing `version` keyword parameter in script argparser

---

.github/workflows/test_package.yaml
requirements.txt

Relax the Python package version requirements: constrain versions within
a range, and test the min and max versions so that there is some more
flexibility when using different package versions.

ENH: Relax the Python package version requirements

---

MANIFEST.in
setup.py

- BUG: Use a single author-email in `setup.py`
- BUG: Set the long description content type to Markdown
- BUG: Remove non-existing pattern under `doc` in `MANIFEST.in`

BUG: Miscellaneous cleanup for compliance PyPI

---

utilities/tests/test_wm_compute_bundle_feature_population_math.py
utilities/wm_compute_bundle_feature_population_math.py

Add bundle feature population math script: allows to compute the
- difference
- stats
- sum
for each bundle feature across participants according to the values
contained in the provided CSV files.
Add the corresponding test.

ENH: Add bundle feature population math script

---

requirements.txt

Specify `statsmodels` package version for Python>=3.10.

ENH: Specify `statsmodels` package version for Python>=3.10

---

.github/workflows/test_package.yaml

Install package using `pip` in GHA workflow following the recommended way for package installation.
Prefer:
```
$ pip install -e .
```
over
```
python setup.py install
```

ENH: Install package using `pip` in GHA workflow

---

.github/workflows/test_package.yaml

Test with code coverage in GHA package test workflow.
Move the coverage reporting block in the workflow file closer to the testing with coverage block.

ENH: Test with code coverage in GHA package test workflow

---

utilities/wm_compute_bundle_feature_population_math.py

Set the hemisphere location name to the correct name in the bundle feature population math script.

ENH: Set the hemisphere location name to the correct name

---

bin/wm_append_clusters_to_anatomical_tracts.py
utilities/tests/test_wm_query_atlas_bundle_names.py
utilities/wm_query_atlas_bundles_names.py
whitematteranalysis/anatomy/org_atlas_utils.py
whitematteranalysis/anatomy/tests/test_org_atlas_utils.py
whitematteranalysis/data/atlas/org_atlas_bundles_v1_1.csv
whitematteranalysis/data/atlas/org_atlas_bundles_v1_1_1.csv
whitematteranalysis/data/atlas/org_atlas_bundles_v1_2.csv
whitematteranalysis/data/atlas/org_atlas_bundles_v1_3a.csv
whitematteranalysis/data/atlas/org_atlas_bundles_v1_3b.csv
whitematteranalysis/data/atlas/org_atlas_bundles_v1_4.csv
whitematteranalysis/data/atlas/org_atlas_version.json
whitematteranalysis/data/atlas/tests/test_utils.py
whitematteranalysis/data/atlas/utils.py
whitematteranalysis/fileio/utils.py

Build bundle list dynamically depending on atlas version.
Add the accompanying files:
- The atlas bundle data (bundle label, short and long names) as CSV files.
- The utilities functions required to read the bundle data.
- Provide some level of encapsulation when adding the methods.
Add a utility script to query the bundles corresponding to the files in an atlas available in a local disk.
Add the corresponding tests.

ENH: Build bundle list dynamically depending on atlas version

---

bin/wm_append_clusters_to_anatomical_tracts.py

Remove trailing semicolons.
Fixes:
```
Trailing semicolon in the statement
```

STYLE: Remove trailing semicolons

---

whitematteranalysis/cluster.py

Fix typo in `cluster` module printed message.
Left behind in commit 8f5c274.

DOC: Fix typo in `cluster` module printed message

---

.readthedocs.yaml
doc/conf.py
doc/index.rst

Fix Sphinx documentation:
- Add a pre-build task to the `readthedocs` config file in order to
generate the `rst` files from the package docstrings so that Sphinx
build the HTML files from them.
- Add the `napoleon` extension to the Sphinx config file so that it can
parse NumPy and Google style docstrings.
- Fix the `index.rst` file so that the package API is effectively
displayed: set `whitematterpackage` as the entry for the reference
section.
- Set the `bin` and `utilities` packages as the entries for the scripts
section in the `index.rst` file.

DOC: Fix Sphinx documentation

---

.readthedocs.yaml
doc/conf.py
doc/index.rst

Add Markdown tutorial files to the documentation.
Add the necessary Sphinx extensions and source suffixes for Sphinx to be able to render the Markdown files.
Documentation:
https://www.sphinx-doc.org/en/master/usage/markdown.html

DOC: Add Markdown tutorial files to the documentation

---

.readthedocs.yaml
doc/conf.py

Prefer using `furo` theme for Sphinx documentation.
Install the `furo` package as a pre-build step so that it is available for `readthedocs`.
Documentation:
https://pradyunsg.me/furo/quickstart/

DOC: Prefer using `furo` theme for Sphinx documentation

---

whitematteranalysis/cluster.py
whitematteranalysis/register_two_subjects.py
whitematteranalysis/register_two_subjects_nonrigid.py
whitematteranalysis/register_two_subjects_nonrigid_bsplines.py

Do not `try`/`except` on non-optional imports.
Also, raise an exception if the corresponding option is not found.

ENH: Do not `try`/`except` on non-optional imports

---

README.md

Fix broken documentation links in `README` file: links became broken with the changes in commit 09682e7. Fix them by using as targets the URLs of the corresponding pages at the `readthedocs`-deployed documentation website.
Fixes #218.

DOC: Fix broken documentation links in `README` file

---

setup.py

Include data files in package installation.
Fixes #216.

BUG: Include data files in package installation

---

bin/wm_cluster_remove_outliers.py

Import `joblib` modules in cluster outlier removal script.
Fixes:
```
File /bin/wm_cluster_remove_outliers.py, line 256, in main
logtrs = Parallel(n_jobs=number_of_jobs, verbose=0)(
NameError: name 'Parallel' is not defined
```
Inadvertently removed in commit f66b337.
Fixes #224.

BUG: Import `joblib` modules in cluster outlier removal script

---

bin/wm_harden_transform.py

Remove a spare `f` when redirecting the output of a 3D Slicer command
call using an f-string in the transform hardening script.
Inadvertently introduced in commit ac6040f.

BUG: Remove spare `f` in an f-string

---

.github/workflows/test_package.yaml

Fix artifact upload naming conflict:
- Add the label of the required version mode to the artifact name.
- Pin action version.
In v4, artifacts are immutable (unless deleted), so each of the uploaded artifacts needs to have a different name.
Fixes:
```
Error: Failed to CreateArtifact: Received non-retryable error:
Failed request: (409) Conflict:
an artifact with this name already exists on the workflow run
```
raised for example in
https://github.com/SlicerDMRI/whitematteranalysis/actions/runs/7407939750

ENH: Fix artifact upload naming conflict

---

whitematteranalysis/congeal_multisubject.py
whitematteranalysis/congeal_to_atlas.py

Fix formatting of numbers that can be floats when creating filenames and dirnames: when transitioning to f-strings (commit ac6040f), it was assumed that `sigma` and `nonrigid_grid_resolution` would be integers, based on the existing formatting. However, these attributes can be set to non-integer values. The pre-f-string transition solution, e.g.:
```
"iteration_%05d_sigma_%05d" % (self.total_iterations, self.sigma)
```
trimmed the decimal part, and thus, for e.g. `total_iterations` 20 and `sigma` 7.5, it would produce:
```
'iteration_00020_sigma_00007'
```
With the introduction of f-strings, i.e.
```
f"iteration_{self.total_iterations:05d}_sigma_{self.sigma:05d}"
```
this would produce an error, since the `sigma` floating point value cannot be formatted as an integer:
``` …
```

STYLE: Fix filename and dirname creation floating point formatting

---

.github/workflows/check_format.yaml
.github/workflows/test_package.yaml

Fix format linter and testing  workflow actions warnings linked to `Node.js`: bump `actions/setup-python` to v5.
Take advantage of the commit to bump `actions/cache` to v4.
Fixes:
```
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20:
actions/setup-python@v4.
For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
raised for example in:
https://github.com/SlicerDMRI/whitematteranalysis/actions/runs/9719632509

ENH: Fix workflow actions warnings linked to `Node.js`

---

requirements.txt
whitematteranalysis/congeal_multisubject.py

Fix formatting of numbers that can be floats when creating the registration process id string: when transitioning to f-strings (commit https://github.com/SlicerDMRI/whitematteranalysis/commit/ac6040fcf77ac132d0fc4a071af9d80240f7f577), it was assumed that `sigma` and `grid_resolution` would be integers, based on the existing formatting. However, these attributes can be set to non-integer values. The pre-f-string transition solution, e.g.:
```
"(...)_sigma_%03d_grid_%03d" % (subject_idx, iteration_count, sigma, grid_resolution)
```
trimmed the decimal part, and thus, for e.g. `sigma` 7.5 and `grid_resolution` 1.5, it would produce:
```
'(...)_sigma_007_grid_001'
```
With the introduction of f-strings, i.e.
```
f"(...)_sigma_{sigma:03d}_grid_{grid_resolution:03d}"
```
this would produce an …

STYLE: Fix registration process id string floating point formatting

---

setup.py

The current `setup.py` does not put all `whitematteranalysis/bin/*` scripts into installed Python's `bin/` directory. As a result, your primary script `wm_apply_ORG_atlas_to_subject.sh` is not put in Python's `bin/` directory. But this was not the case in prior version of whitematteranalysis. This breaking change was introduced by this commit: https://github.com/SlicerDMRI/whitematteranalysis/commit/ed933b38cfd5c9de15f3d0b59e37f5696c52e354. We are submitting a fix for this.
cc @yrathi @ryanZurrin

Put wm_apply_ORG_atlas_to_subject.sh in Python's bin/ directory
